/**
 * Flattens the @import tree into one stylesheet.
 *
 * The sources stay split, because thirty rules in one file is not a system
 * and the split is how the layers stay legible. What ships is one file.
 *
 * ── Why this is worth a build step in a repo that avoided one ─────────────
 * The @import version made 22 requests for one page. Browsers cannot discover
 * a nested import until the parent has parsed, so those go out in serial
 * waves rather than in parallel, and every wave is a chance to paint
 * unstyled.
 *
 * It is also a cache hazard, and that is not theoretical: a stale
 * panelware.css that predated one new @import meant the new file was never
 * requested at all. The dialog rendered with no title bar, no blue ground and
 * its close button fallen out of the header, and nothing anywhere reported an
 * error. One missing file in a chain silently removes a component's entire
 * styling.
 *
 * Every kit this one cites ships a single file. So does this now.
 *
 * ── url() rewriting is the part that is easy to get wrong ─────────────────
 * css/components/icon.css reaches its sheet at ../../assets/icons.svg.
 * Inlined into css/panelware.css, one level shallower, that path is wrong by
 * a directory and the icons silently stop painting. Every relative url() is
 * rewritten from its source file's directory to the output's.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');

const IMPORT = /^@import\s+"([^"]+)"(?:\s+layer\(([^)]+)\))?\s*;\s*$/gm;
const URL_REF = /url\(\s*(['"]?)([^'")]+)\1\s*\)/g;

/** Rewrites relative url()s so they still resolve from the output file. */
function rebase(css, fromDir, toDir) {
  return css.replace(URL_REF, (whole, quote, ref) => {
    if (/^(?:[a-z]+:|\/|#|data:)/i.test(ref)) return whole;
    const abs = resolve(fromDir, ref);
    const next = relative(toDir, abs).split('\\').join('/');
    return `url("${next}")`;
  });
}

/**
 * Inlines every import, depth first, in source order.
 *
 * A file imported twice is emitted once: @import is idempotent in the
 * cascade, concatenation is not, and a second copy of a component's rules
 * would win over a consumer override that was written to beat the first.
 */
function flatten(entry, outDir, seen = new Set()) {
  const abs = resolve(entry);
  if (seen.has(abs)) return '';
  seen.add(abs);

  const dir = dirname(abs);
  const source = readFileSync(abs, 'utf8');
  let out = '';
  let last = 0;

  for (const m of source.matchAll(IMPORT)) {
    out += rebase(source.slice(last, m.index), dir, outDir);
    const child = flatten(resolve(dir, m[1]), outDir, seen);
    out += m[2] ? `@layer ${m[2]} {\n${child}\n}\n` : child;
    last = m.index + m[0].length;
  }
  out += rebase(source.slice(last), dir, outDir);
  return out;
}

export function bundle(entryRel) {
  const entry = join(ROOT, entryRel);
  const outDir = join(ROOT, 'css');
  const header = `/* GENERATED by scripts/build-css.mjs from ${entryRel}. Do not edit.\n` +
    `   Edit the sources under css/ and run \`npm run generate\`. */\n\n`;
  return header + flatten(entry, outDir).replace(/\n{3,}/g, '\n\n');
}

if (import.meta.url === `file://${process.argv[1]}`) {
  for (const [entry, out] of [
    ['css/_panelware.css', 'css/panelware.css'],
    ['css/tokens/index.css', 'css/tokens.css'],
  ]) {
    const css = bundle(entry);
    writeFileSync(join(ROOT, out), css);
    console.log(`${out.padEnd(20)} ${css.split('\n').length} lines, ${(css.length / 1024).toFixed(1)}kB`);
  }
}
